[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
script = "scripts"
test = "test"
cache_path = "cache"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"
evm_version = "paris"
